version: "3"

services:
    db:
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: my_database
        volumes:
            - data:/data/db

volumes:
    data:
